services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb:Z
      - ./influxdb/config:/etc/influxdb:Z

  telegraf:
    image: telegraf:1.27
    environment:
      HOSTNAME: "telegraf-getting-started"
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      - ./telegraf:/etc/telegraf:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    privileged: true

  kapacitor:
    image: kapacitor:1.5
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - "9092:9092"
    volumes:
      - ./kapacitor/data:/var/lib/kapacitor:Z
      - ./kapacitor/config:/etc/kapacitor:Z

  chronograf:
    image: chronograf:1.7
    depends_on:
      - influxdb
      - kapacitor
      - telegraf
    ports:
      - "8888:8888"
    volumes:
      - ./chronograf/data:/var/lib/chronograf:Z
    links:
      - influxdb
      - kapacitor
